[project]
name = "right_coding_agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "ddgs>=9.13.0",
    "deepagents>=0.5.1",
    "faster-whisper>=1.2.1",
    "html-to-markdown>=3.1.0",
    "httpx>=0.28.1",
    "langchain>=1.0.0",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.12",
    "lmdb>=2.3.0",
    "loguru>=0.7.3",
    "mss>=10.2.0",
    "numpy>=2.4.4",
    "opencv-python-headless>=5.0.0.93",
    "optimum-quanto>=0.2.7",
    "peft>=0.20.0",
    "pillow==11.1.0",
    "prompt-toolkit>=3.0.52",
    "pydantic-settings>=2.13.1",
    "pynput>=1.8.2",
    "pyperclip>=1.11.0",
    "rich>=14.3.3",
    "sounddevice>=0.5.5",
    "torch==2.11.0",
    "torchvision==0.26.0",
    "transformers==4.57.1",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu128", marker = "sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
    "black>=26.5.1",
    "flake8>=7.3.0",
]

[tool.black]
target-version = ["py312"]
line-length = 120
