"""The whitelist policy: which syntax and which methods scripts may use.

Everything is opt-in — AST node types and attribute access alike. Anything
outside these tables is rejected before or during execution, so widening the
script language means extending them here (and updating the `run_tools`
docstring that documents the language to the model).
"""

import ast

ALLOWED_NODES = {
    ast.Module,
    ast.Expr,
    ast.Assign,
    ast.AugAssign,
    ast.AnnAssign,
    ast.If,
    ast.For,
    ast.While,
    ast.Break,
    ast.Continue,
    ast.Pass,
    ast.Try,
    ast.ExceptHandler,
    ast.Return,
    ast.Raise,
    ast.BoolOp,
    ast.BinOp,
    ast.UnaryOp,
    ast.Compare,
    ast.IfExp,
    ast.Call,
    ast.Name,
    ast.Constant,
    ast.Attribute,
    ast.Subscript,
    ast.List,
    ast.Tuple,
    ast.Dict,
    ast.Set,
    ast.Slice,
    ast.JoinedStr,
    ast.FormattedValue,
    ast.ListComp,
    ast.DictComp,
    ast.comprehension,
    ast.Load,
    ast.Store,
    ast.Del,
    ast.And,
    ast.Or,
    ast.Not,
    ast.Add,
    ast.Sub,
    ast.Mult,
    ast.Div,
    ast.FloorDiv,
    ast.Mod,
    ast.Pow,
    ast.USub,
    ast.UAdd,
    ast.Eq,
    ast.NotEq,
    ast.Lt,
    ast.LtE,
    ast.Gt,
    ast.GtE,
    ast.In,
    ast.NotIn,
    ast.Is,
    ast.IsNot,
    ast.Starred,
    ast.keyword,
}

# Safe methods reachable via attribute access (obj.method). No dunders ever.
SAFE_METHODS = {
    str: {
        "lower",
        "upper",
        "strip",
        "lstrip",
        "rstrip",
        "split",
        "rsplit",
        "join",
        "replace",
        "startswith",
        "endswith",
        "find",
        "count",
        "title",
        "capitalize",
        "zfill",
        "isdigit",
        "isalpha",
    },
    list: {
        "append",
        "extend",
        "pop",
        "insert",
        "remove",
        "index",
        "count",
        "sort",
        "reverse",
        "copy",
        "clear",
    },
    dict: {"get", "keys", "values", "items", "pop", "update", "copy", "clear"},
    set: {"add", "remove", "discard", "union", "intersection", "difference"},
    tuple: {"index", "count"},
}
